general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = pidof hyprlock || hyprlock
    after_sleep_cmd = hyprctl dispatch dpms on
    ignore_dbus_inhibit = false
}

# 10 min — lock screen
listener {
    timeout = 600
    on-timeout = mpvpaper -o "no-audio --loop" HDMI-A-2 ~/Pictures/Wallpapers/green-forest-moewalls-com.mp4
    on-resume = pkill mpvpaper
}

# 15 min — displays off
listener {
    timeout = 900
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# 60 min — suspend
listener {
    timeout = 3600
    on-timeout = systemctl suspend
}
