background {
    monitor =
    path = ~/Pictures/Wallpapers/2025-07-04-18-09-13-pexels-eberhardgross-691668.jpg
    blur_passes = 3
    blur_size = 3
    brightness = 0.7
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    outer_color = rgb(7fbbb3)
    inner_color = rgb(2d353b)
    font_color = rgb(d3c6aa)
    placeholder_text = <i>Password...</i>
    position = 0, -100
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgba(d3c6aaf0)
    font_size = 72
    font_family = JetBrainsMono Nerd Font
    position = 0, 200
    halign = center
    valign = center
}
